[MTDSA-10599]Added create and amend foreign submission RAML
hmrc/property-business-api pull request #163
Opened 2021-11-29 17:07 UTC by vfryer12

2021-11-30 11:16 UTC, BetaDraconis commented on resources/public/api/conf/2.0/schemas/foreign_property_annual_submission_create_and_amend/request.json
> +                      "minimum": 0.01,
These two lines need their values to be swapped.

2021-12-02 08:56 UTC, HarryBaxter requested changes

2021-12-02 08:56 UTC, HarryBaxter commented on resources/public/api/conf/2.0/examples/foreign_property_annual_submission_create_and_amend/request.json
> +      "propertyIncomeAllowance": 4004.49
This would cause both RULE_BOTH_ALLOWANCES_SUPPLIED and RULE_PROPERTY_INCOME_ALLOWANCE errors.  Need to take propertyIncomeAllowance out.

2021-12-02 08:56 UTC, HarryBaxter commented on resources/public/api/conf/2.0/examples/foreign_property_annual_submission_create_and_amend/request.json
> +        "propertyIncomeAllowance": 4002.29,
Same as above

2021-12-02 08:56 UTC, HarryBaxter commented on resources/public/api/conf/2.0/examples/foreign_property_annual_submission_create_and_amend/request.json
> +              "qualifyingDate": "2020-03-29T00:00:00.000Z",
Should be in the format YYYY-MM-DD

2021-12-02 08:56 UTC, HarryBaxter commented on resources/public/api/conf/2.0/examples/foreign_property_annual_submission_create_and_amend/response.json
> +      "href":"/individuals/business/property/foreign/{nino}/{businessId}/annual/{taxYear}",
Can you replace the parameter names with examples

2021-12-02 08:56 UTC, HarryBaxter commented on resources/public/api/conf/2.0/schemas/foreign_property_annual_submission_create_and_amend/request.json
> +          "description": "Object holding Foreign FHL EEA Property Adjustments",
Full stop at the end

2021-12-02 08:56 UTC, HarryBaxter commented on resources/public/api/conf/2.0/schemas/foreign_property_annual_submission_create_and_amend/request.json
> +      "description": "Object holding the adjustments and allowances of the user's Furnished Holiday Lets in the European Economic Area for the period",
Full stop at the end

2021-12-02 08:56 UTC, HarryBaxter commented on resources/public/api/conf/2.0/schemas/foreign_property_annual_submission_create_and_amend/request.json
> +            "description": "Object holding foreign Non FHL Property Allowances",
Full stop at the end

2021-12-02 08:56 UTC, HarryBaxter commented on resources/public/api/conf/2.0/schemas/foreign_property_annual_submission_create_and_amend/request.json
> +                "description": "Details about structured building allowances",
Full stop at the end

2021-12-02 08:56 UTC, HarryBaxter commented on resources/public/api/conf/2.0/schemas/foreign_property_annual_submission_create_and_amend/request.json
> +                          "description": "The date qualified for structured building allowance.\n\nMust conform to the format YYYY-MM-DD",
Full stop at the end

2021-12-02 08:56 UTC, HarryBaxter commented on resources/public/api/conf/2.0/schemas/foreign_property_annual_submission_create_and_amend/request.json
> +                      "additionalProperties": false,
not needed if there are mandatory fields

2021-12-02 08:56 UTC, HarryBaxter commented on resources/public/api/conf/2.0/schemas/foreign_property_annual_submission_create_and_amend/request.json
> +                      "additionalProperties": false,
not needed if there are mandatory fields

2021-12-02 08:56 UTC, HarryBaxter commented on resources/public/api/conf/2.0/schemas/foreign_property_annual_submission_create_and_amend/request.json
> +                      "description": "Object holding foreign Non FHL structured building details.\nPost code is mandatory and minimum one of name and number field must be supplied",
Full stop at the end

2021-12-02 08:56 UTC, HarryBaxter commented on resources/public/api/conf/2.0/schemas/foreign_property_annual_submission_create_and_amend/request.json
> +                  "additionalProperties": false,
not needed if there are mandatory fields

2021-12-02 08:56 UTC, HarryBaxter commented on resources/public/api/conf/2.0/schemas/foreign_property_annual_submission_create_and_amend/request.json
> +        "additionalProperties": false,
not needed if there are mandatory fields

2021-12-02 12:28 UTC, merged